# Phân phối

## Phân phối Bernoulli
::: {#def-bernoulli}
### Bernoulli distribution
$X\sim\Ber(p)$
có
$$
\P(X=1) = p = 1-\P(X=0)
$$
và
$\E{X} = p, \V{X} = p(1-p)$.
:::

## Phân phối nhị thức
::: {#def-binomial}
### Binomial distribution
$K\sim\Binom(n, p)$
với $n\in\N, p\in(0,1)$
mô tả tổng số lần thành công
của $n$ thí nghiệm độc lập
$K_1,\ldots,K_n \iid \Ber(p).$
Ta có
$$
\P(K=k) = \binom{n}{k}p^{k}(1-p)^{n-k}
$$
và
$\E{K} = np, \V{K} = np(1-p)$.
:::

## Phân phối Poisson
:::{#def-poisson}
### Phân phối Poisson
$K\sim\Poiss(\lambda),$
$\lambda > 0$ cố định,
có
$$
\P(K=k) = e^{-\lambda}
\frac{\lambda^k}{k!},
$$
$k=0,1,2,\ldots$ là số lần phát sinh sự kiện trong một giới hạn cố định,
các sự kiện phát sinh độc lập.
$$\E{K} = \V{K} = \lambda
.$$
:::

Khi $n$ đủ lớn và $p$ đủ nhỏ thì
$\Poiss(np)$ gần với $\Binom(n,p)$.

## Phân phối hình học

:::{#def-geomdist}
### Geometric distribution
$K\sim\Geom(p), p \in (0,1)$
có
$$
\P(K=k)=p(1-p)^{k-1}, k=1,2,\ldots
$$
là xác suất thành công đầu tiên xảy ra sau đúng $k$ lần thực nghiệm
$\Ber(k).$
$$\E{K}=1/p,\V{K}=(1-p)/p^2.$$

:::

## Phân phối đều
:::{#def-uniform}
### Uniform distribution
$X\sim\Unif[a,b]$ có mật độ
$$
f(x)\is
\frac{x-a}{b-a}
\textrm{ for }
x\in[a,b].
$$
:::
:::{.remark}
$$\E{X} = \frac{a+b}{2}, \V{X}=\frac{(b-a)^2}{12}.$$
:::

:::{.remark}
Nếu biến $X$ có cdf $F$ (@def-cdf) khả nghịch thì
$F(X)\sim\Unif[0,1].$
:::

## Phân phối mũ
:::{#def-expdist}
### Exponential distribution
$X\sim\text{Exp}(\lambda)$
có
$$
f(x)={\lambda}e^{-\lambda x},x\in\R_{\geq 0},
$$
$x$ ước lượng khoảng cách giữa hai lần phát sinh
sự kiện trong quá trình $\Poiss(\lambda).$
$$\E{X}=1/\lambda,\V{X}=1/\lambda^2.$$
:::

## Phân phối chuẩn
:::{#def-gaussian}
### Normal/Gaussian Distribution
Phân phối chuẩn
$X\sim\Gaus{\mu, \sigma^2}$ có
mật độ
$$
f(x) =
\frac{1}{\sqrt{\pi 2\sigma^2}}\exp\left(-\frac{(x-\mu)^2}{2\sigma^2}\right),
x\in\R.
$$
:::
:::{.remark}
$\E{X}=\mu,\V{X}=\sigma^2$.
:::
:::{#def-standard-normal-dist}
### Standard Normal Distribution
$\Gaus{0,1}$ là **phân phối chuẩn tắc**.
:::

:::{#thm-sum-gaussian}
### Cộng phân phối chuẩn
Nếu
$X_i \sim\Gaus{\mu_i, \sigma_i^2}, i=1,\ldots,n$
độc lập thì

$$\sum_{i=1}^n X_i\sim
\Gaus{\sum_{i=1}^n \mu_i, \sum_{i=1}^n \sigma_i^2}
.$$
:::

:::{#def-gaussian-vector}
### Multivariate normal distribution, or joint normal distribution
Nếu mọi tổ hợp tuyến tính các yếu tố của
vector $\boldsymbol{v}$ đều
thuộc phân phối chuẩn 1 biến thì
$\boldsymbol{v}$
được gọi là một vector phân phối chuẩn.
:::

## Phân phối $\chi^2$
:::{#def-chi-dist}
### Phân phối $\chi^2$
$X\sim\chi_k^2$ là
tổng bình phương của
$X_1,\ldots,X_k\iid\Gaus{0, 1}$

$$
X \is \sum_{i=0}^k X_i^2
$$

và có
$\E{X}=k,\V{X}=2k$.
:::

## Phân phối Student
:::{#def-student-dist}
### Student's T distribution

Nếu có $Z\sim\Gaus{0, 1}, V\sim \chi_k^2$ độc lập với nhau thì

$$
X \is \frac{Z}{\sqrt{V/k}}
$$

tuân theo phân phối Student's $t_k$.
:::

## Phân phối Beta
:::{#def-beta-dist}
### Beta distribution
$X\sim\Betad{\alpha, \beta},$
tham số
$\alpha>0,\beta>0$
có mật độ trên $x\in [0,1]$ là
$$
f(x) = \frac{x^{\alpha-1}(1-x)^{\beta-1}}{B(\alpha,\beta)}
,
$$
$B(\alpha,\beta)$ là hằng số chuẩn hóa.
:::
:::{.remark}
$$
\begin{split}
\E{X}&=\frac{\alpha}{\alpha+\beta},\\
\V{X}&=\frac{\alpha \beta }{(\alpha +\beta )^2(\alpha + \beta + 1)},\\
\argmax f &= \frac{\alpha -1}{\alpha +\beta -2} \text { for } \alpha ,\beta > 1.
\end{split}
$$
:::

:::{.remark}
Phân phối Beta có đồ thị rất linh hoạt trên khoảng $[0,1],$
phù hợp làm xác suất tiền nghiệm (@def-bayesian-method).
:::

:::{#exm-unif-beta}
$\Unif[0,1] = \Betad{1, 1}.$
:::

## Phân phối Gamma

:::{#def-gamma-dist}
### Gamma distribution
với tham số $q>0$ (shape), $\lambda>0$ (rate)
có mật độ là
$$
f(x)\is\frac{\lambda^q x^{q-1} e^{-\lambda x}}{\Gamma(q)}
 \quad \forall
x\in (0,\infty)
,
$$
$\Gamma$ là hàm Euler Gamma.
:::
:::{.remark}
$$\E{X} = q/\lambda.$$
:::
