project:
  type: book

book:
  title: XSTK
  subtitle: "Xác Suất Thống Kê"
  output-file: xstk
  author: "Võ Chí Công"
  # date: "2022/8/25"
  downloads: pdf
  chapters:
    - index.qmd
    - part: "Xác suất"
      chapters:
        - 10-proba-intro.qmd
        - 13-distributions.qmd
        - 15-proba-converge.qmd
    - part: "Thống kê"
      chapters:
        - 20-stat-intro.qmd
        - 30-est-method.qmd
        - 40-hypothesis-test.qmd
    - references.qmd
  repo-url: https://github.com/vochicong/xstk
  sharing: [twitter, facebook]
  # sidebar:
  #   style: docked
  #   background: dark

comments:
  hypothesis: true

bibliography: references.bib

format:
  html:
    theme: cosmo
    include-before-body: preamble.md
    # toc-title: TOC
    toc-depth: 3
    # toc-location: left
    # Using katex solve the xrightarrow problem, but
    # html-math-method: katex
  pdf:
    documentclass: scrreprt
    colorlinks: true
    include-in-header: preamble.tex
    include-after-body:
      text: |
        \printindex

crossref:
  fig-title: Fig
  fig-prefix: Fig
  def-title: Def
  def-prefix: Def
  thm-title: Thm
  thm-prefix: Thm
