project:
  type: book

book:
  title: XSTK
  subtitle: "Xác Suất Thống Kê"
  output-file: xstk
  author: "Võ Chí Công"
  # date: "2022/8/25"
  downloads: pdf
  chapters:
    - index.qmd
    - notation.qmd
    - part: "Xác suất"
      chapters:
        - 10-proba-intro.qmd
        - 20-distributions.qmd
        - 30-proba-converge.qmd
    - part: "Thống kê"
      chapters:
        - 40-stat-intro.qmd
        - 50-est-method.qmd
        - 60-hypothesis-test.qmd
        - 70-bayes-stat.qmd
    - part: "Hồi quy"
      chapters:
        - 80-linear-regression.qmd
    - references.qmd
  repo-url: https://github.com/vochicong/xstk
  # sharing: [twitter, facebook]
  # sidebar:
  #   style: docked
  #   background: dark

# comments:
#   hypothesis: true

bibliography: references.bib

format:
  html:
    theme: cosmo
    include-before-body: preamble.md
    # toc-title: TOC
    toc-depth: 3
    # toc-location: left
    # Using katex solve the xrightarrow problem, but
    # html-math-method: katex
  pdf:
    # documentclass: scrreprt
    geometry:
      - top=5mm
      - bottom=25mm
      - left=5mm
      - right=5mm
    colorlinks: true
    include-in-header: preamble.tex
    fontfamily: libertinus
    fontfamilyoptions:
      - osf
      - p
    fontsize: 14pt
    lang: vi

crossref:
  exm-title: Ví dụ
  fig-title: Hình
  fig-prefix: H
  def-title: Định nghĩa
  def-prefix: ĐN
  thm-title: Định lý
  thm-prefix: ĐL
  cor-title: Hệ quả
  cor-prefix: HQ
