project:
  type: book

book:
  title: "Xác Suất Thống Kê"
  author: "Võ Chí Công"
  date: "2022/8/25"
  downloads: pdf
  chapters:
    - index.qmd
    - 10-proba-intro.qmd
    - 20-stat-intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    include-before-body: preamble.md
  pdf:
    documentclass: scrreprt
    include-in-header: preamble.tex

crossref:
  fig-title: Fig
  fig-prefix: Fig
  def-title: Def
  def-prefix: Def
  thm-title: Thm
  thm-prefix: Thm
