project:
  type: book

book:
  title: "Xác Suất Thống Kê"
  author: "Võ Chí Công"
  # date: "2022/8/25"
  downloads: pdf
  chapters:
    - index.qmd
    - 10-proba-intro.qmd
    - 15-proba-converge.qmd
    - 20-stat-intro.qmd
    - 30-est-method.qmd
    - references.qmd
  repo-url: https://github.com/vochicong/xstk
  repo-actions: [edit, issue, source]
  sharing: [twitter, facebook]
  # sidebar:
  #   style: docked
  #   background: dark

comments:
  hypothesis: true

bibliography: references.bib

format:
  html:
    theme: cosmo
    include-before-body: preamble.md
    # toc-title: TOC
    toc-depth: 3
    # toc-location: left
  pdf:
    documentclass: scrreprt
    include-in-header: preamble.tex

crossref:
  fig-title: Fig
  fig-prefix: Fig
  def-title: Def
  def-prefix: Def
  thm-title: Thm
  thm-prefix: Thm
